### ISSUE TITLE
Multiple validators?

### ISSUE THREAD

**Issue by rohan-sircar** [magiclen/validators#1]
The crate does not support multiple validators at the same time it seems?
``` rust
#[derive(Validator, Debug, Clone)]
#[validator(line(char_length(min = 5, max = 35),regex(regexs::USERNAME_REG))]
pub struct Username(String);
```
does not compile and
``` rust
#[derive(Validator, Debug, Clone)]
#[validator(regex(regexs::USERNAME_REG))]
#[validator(line(char_length(min = 5, max = 35)))]
pub struct Username(String);
```
doesn't work, only the top one is selected

**Comment by magiclen** [comment]
A struct cannot derive multiple validators. And there are no plans for that.

In your case, you can just use your regex to limit the length (using `{5, 35}`).

**Comment by rohan-sircar** [comment]
Okay no problem. I still like how the create follows the "parse, don't validate" and newtype patterns with serde integration. I'll go with your suggestion. Thanks!
