### ISSUE TITLE
Email with two '@' signs are wrongfully accepted

### ISSUE THREAD

**Issue by rien** [magiclen/validators#3]
Hi there

I was testing a Rocket application and used `invalid@email@example.com` to test for invalid emails, but it was wrongfully accepted.

Can this be fixed? (I could make a PR if you point me in the right direction).

Thanks!

**Comment by magiclen** [comment]
Hi, it should be fixed in 0.20.5. Thank you.

**Comment by rien** [comment]
Thank you for the blazingly fast reaction! I can confirm it works now.
